"""Whitelist-oriented release checks; never print a matched secret."""
import argparse,json,re,zipfile,tarfile
from pathlib import Path
FORBIDDEN_PARTS={'.git','.eg','.env.local','requests.sqlite3','STATE.json','PLAN.md','REQUEST.md','AGENTS.md','auth.json','__pycache__','venv'}
ALLOWED_TOP={'.github','.gitignore','.gitattributes','.env.example','README.md','CHANGELOG.md','LICENSE','LICENSES','LICENSING.md','THIRD_PARTY_NOTICES.md','CITATION.cff','pyproject.toml','MANIFEST.in','build_backend.py','requirements-runtime.lock','requirements-dev.lock','config.example.json','config.coding-plan.example.json','context.example.json','docs','research','schemas','profiles','prompts','src','skills','integrations','datasets','evals','tests','scripts','site','reports','examples','platforms'}
def inspect_names(names):
    errors=[]
    for name in names:
        parts=Path(name.replace('\\','/')).parts
        if any(p in FORBIDDEN_PARTS for p in parts) or '..' in parts:errors.append({'path':name,'kind':'private_or_unsafe_path'})
    return errors
def scan(root,paths,secrets=()):
    root=Path(root);errors=inspect_names(paths)
    for name in paths:
        path=root/name
        if not path.is_file():errors.append({'path':name,'kind':'missing'});continue
        if Path(name).parts[0] not in ALLOWED_TOP:errors.append({'path':name,'kind':'not_allowlisted'})
        raw=path.read_bytes()
        if any(value and value.encode() in raw for value in secrets):errors.append({'path':name,'kind':'credential_match'})
        try:text=raw.decode('utf-8')
        except UnicodeDecodeError:continue
        if re.search(r'(?i)(?:sk-[A-Za-z0-9_-]{24,}|-----BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY-----)',text):errors.append({'path':name,'kind':'secret_pattern'})
        if re.search(r'(?i)(?:D:[\\/]+(?:Codex|Documents)|C:[\\/]+Users[\\/]+)',text):errors.append({'path':name,'kind':'personal_absolute_path'})
        if re.search(r'(?i)(?:generated by codex|built with ai|ai-generated code|co-authored-by:.*(?:codex|openai))',text) and not name.startswith(('tests/','scripts/')):errors.append({'path':name,'kind':'publication_residue'})
    return {'status':'pass' if not errors else 'fail','files':len(paths),'errors':errors}
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--root',default='.');p.add_argument('--manifest',required=True);a=p.parse_args()
    result=scan(a.root,json.loads(Path(a.manifest).read_text(encoding='utf-8')));print(json.dumps(result,ensure_ascii=False,indent=2));raise SystemExit(result['status']!='pass')
